services:
  stats-server:
    build: stats/server
    image: stats-server-image
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statsdb
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  stats-db:
    image: postgres:16.1
    container_name: stats-db-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=statsdb

  ewm-service:
    build: main
    image: main-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - main-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/maindb
      - SPRING_DATASOURCE_USERNAME=dbuser2
      - SPRING_DATASOURCE_PASSWORD=1234567

  main-db:
    image: postgres:16.1
    container_name: main-db-postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=1234567
      - POSTGRES_USER=dbuser2
      - POSTGRES_DB=maindb

