create table categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_category_name UNIQUE (name),
    CONSTRAINT pk_category_id PRIMARY KEY (id)
);

create table users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(250) NOT NULL,
    CONSTRAINT uq_user_email UNIQUE (email),
    CONSTRAINT pk_user_id PRIMARY KEY (id)
);
